// https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
export const theme = {
  'primary-color': '#764ba2',
  'success-color': '#0bb20c',
  'info-color': '#0b84f4',
  'warning-color': '#f58003',
  'error-color': '#f5222d',
  'icon-color-hover': '#000000',
  'heading-color': '#191919',
  'text-color': '#404040',
  'text-color-secondary': '#737373',
  'text-color-inverse': '#ffffff',
  'border-color-base': '#cccccc',
  'layout-header-background': '#2e2e2e',
  'font-size-base': '13px',
  'border-radius-base': '2px',
  'disabled-color': '#a6a6a6',
  'disabled-bg': '#efefef',
  'shadow-color': 'rgba(0, 0, 0, 0.20)',
  'background-color-light': '#f5f5f5',
  'background-color-base': '#efefef',
  'item-hover-bg': '#e8e8e8',
  'btn-font-weight': '500',
  'btn-border-radius-base': '2px',
  'btn-border-radius-sm': '2px',
  'btn-default-border': '#BBBBBB',
  'btn-danger-color': '#ffffff',
  'btn-padding-base': '0 12px',
  'btn-font-size-sm': '12px',
  'btn-padding-lg': '0 12px',
  'btn-padding-sm': '0 8px',
  'btn-height-base': '26px',
  'btn-height-lg': '32px',
  'btn-height-sm': '22px',
  'btn-primary-bg': '#764ba2',
  'btn-primary-border': '#764ba2',
  'btn-primary-color': '#ffffff',
  'btn-default-bg': '#ffffff',
  'btn-default-color': '#764ba2',
  'btn-danger-bg': '#f5222d',
  'btn-danger-border': '#f5222d',
  'btn-ghost-bg': 'transparent',
  'btn-ghost-color': '#764ba2',
  'btn-ghost-border': '#764ba2',
  'form-item-margin-bottom': '20px',
  'input-height-base': '26px',
  'input-height-lg': '32px',
  'input-height-sm': '22px',
  'input-placeholder-color': '#a6a6a6',
  'input-number-handler-active-bg': '#e8e8e8',
  'input-addon-bg': '#F5F5F5',
  'progress-remaining-color': '#EFEFEF',
  'menu-inline-toplevel-item-height': '32px',
  'menu-item-height': '32px',
  'table-header-bg': '#f0f0f0',
  'table-header-sort-bg': '#EFEFEF',
  'table-expanded-row-bg': '#ffffff',
  'table-padding-vertical': '8px',
  'table-padding-horizontal': '8px',
  'table-border-radius-base': '2px',
  'table-header-bg-sm': '#f0f0f0',
  'badge-status-size': '8px',
  'rate-star-color': '#ffad0a',
  'rate-star-bg': '#EFEFEF',
  'card-padding-base': '16px',
  'card-radius': '2px',
  'tabs-card-height': '32px',
  'tabs-bar-margin': '0 0 12px 0',
  'tabs-horizontal-margin': '0 24px 0 0',
  'tabs-horizontal-padding': '8px 16px',
  'avatar-border-radius': '2px',
  'switch-height': '20px',
  'switch-color': '#0bb20c',
  'pagination-item-size': '24px',
  'slider-rail-background-color': '#efefef',
  'collapse-header-padding': '4px 16px',
  'skeleton-color': '#f0f0f0',
  'transfer-header-height': '32px',
  'message-notice-content-padding': '16px 24px',
  'alert-success-border-color': '#97E789',
  'alert-success-bg-color': '#DFFADE',
  'alert-success-icon-color': '#0bb20c',
  'alert-info-border-color': '#88C5FF',
  'alert-info-bg-color': '#DDEFFF',
  'alert-info-icon-color': '#0b84f4',
  'alert-warning-border-color': '#FFCF70',
  'alert-warning-bg-color': '#FFF2D9',
  'alert-warning-icon-color': '#f58003',
  'alert-error-border-color': '#FFADA8',
  'alert-error-bg-color': '#FFE8E7',
  'alert-error-icon-color': '#f5222d',
  'list-empty-text-padding': '12px',
  'list-item-padding': '8px 0',
  'list-item-meta-margin-bottom': '12px',
  'list-item-meta-avatar-margin-right': '12px',
  'list-item-meta-title-margin-bottom': '8px',
};
